maxGameLength: 700
username: ryanbley3@gmail.com
password: 8ypPEs$N!6!hF&M$vJ9frBK8
authMethod: TokenAuth
authToken: US-0d6c8ebadfe939c281c7af0f6c8264ba-812915332
realm: us.actual.battle.net
characterName: Brac
commandLineArgs: ""
killD2OnStop: true
classicMode: false
closeMiniPanel: false
useCentralizedPickit: false
hidePortraits: false
scheduler:
    enabled: false
    days:
        - dayOfWeek: 0
          timeRange: []
        - dayOfWeek: 1
          timeRange: []
        - dayOfWeek: 2
          timeRange: []
        - dayOfWeek: 3
          timeRange: []
        - dayOfWeek: 4
          timeRange: []
        - dayOfWeek: 5
          timeRange: []
        - dayOfWeek: 6
          timeRange: []
health:
    healingPotionAt: 75
    manaPotionAt: 10
    rejuvPotionAtLife: 50
    rejuvPotionAtMana: 0
    mercHealingPotionAt: 80
    mercRejuvPotionAt: 30
    chickenAt: 30
    mercChickenAt: 10
inventory:
    inventoryLock:
        - - 0
          - 0
          - 0
          - 0
          - 0
          - 1
          - 1
          - 1
          - 1
          - 0
        - - 0
          - 0
          - 0
          - 0
          - 0
          - 1
          - 1
          - 1
          - 1
          - 0
        - - 0
          - 0
          - 0
          - 0
          - 0
          - 1
          - 1
          - 1
          - 1
          - 0
        - - 0
          - 0
          - 0
          - 0
          - 0
          - 1
          - 1
          - 1
          - 1
          - 0
    beltColumns:
        - mana
        - healing
        - healing
        - rejuvenation
character:
    class: nova
    useMerc: true
    stashToShared: false
    useTeleport: true
    berserker_barb:
        find_item_switch: false
        skip_potion_pickup_in_travincal: false
    nova_sorceress:
        boss_static_threshold: 50
    mosaic_sin:
        useTigerStrike: false
        useCobraStrike: false
        useClawsOfThunder: false
        useBladesOfIce: false
        useFistsOfFire: false
game:
    minGoldPickupThreshold: 500000
    useCainIdentify: false
    clearTPArea: true
    difficulty: hell
    randomizeRuns: true
    runs:
        - baal
        - terror_zone
    createLobbyGames: false
    pindleskin:
        skipOnImmunities: []
    cows:
        openChests: true
    pit:
        moveThroughBlackMarsh: true
        openChests: true
        focusOnElitePacks: true
        onlyClearLevel2: true
    andariel:
        clearRoom: false
    stony_tomb:
        openChests: true
        focusOnElitePacks: false
    mausoleum:
        openChests: false
        focusOnElitePacks: false
    ancient_tunnels:
        openChests: true
        focusOnElitePacks: false
    drifter_cavern:
        openChests: true
        focusOnElitePacks: false
    spider_cavern:
        openChests: true
        focusOnElitePacks: false
    arachnid_lair:
        openChests: false
        focusOnElitePacks: false
    mephisto:
        killCouncilMembers: false
        openChests: false
    tristram:
        clearPortal: true
        focusOnElitePacks: false
    nihlathak:
        clearArea: false
    diablo:
        killDiablo: true
        startFromStar: false
        focusOnElitePacks: true
        disableItemPickupDuringBosses: false
        attackFromDistance: 0
    baal:
        killBaal: true
        dollQuit: true
        soulQuit: true
        clearFloors: false
        onlyElites: false
    eldritch:
        killShenk: true
    lowerkurastchests:
        openRacks: true
    terror_zone:
        focusOnElitePacks: true
        skipOnImmunities: []
        skipOtherRuns: false
        areas:
            - 6
            - 12
            - 20
            - 37
            - 39
            - 74
            - 102
            - 108
            - 121
    leveling:
        ensurePointsAllocation: true
        ensureKeyBinding: true
    quests:
        clearDen: false
        rescueCain: false
        retrieveHammer: false
        getCube: false
        killRadament: false
        retrieveBook: false
        killIzual: false
        killShenk: false
        rescueAnya: false
        killAncients: false
companion:
    leader: false
    leaderName: ""
    gameNameTemplate: game-
    gamePassword: xxx
gambling:
    enabled: true
    items:
        - coronet
        - amulet
        - ring
cubing:
    enabled: true
    enabledRecipes:
        - Perfect Amethyst
        - Perfect Diamond
        - Perfect Emerald
        - Perfect Ruby
        - Perfect Sapphire
        - Perfect Topaz
        - Perfect Skull
        - Upgrade Io
        - Upgrade Lum
        - Upgrade Ko
        - Upgrade Fal
        - Reroll GrandCharms
        - Caster Amulet
    skipPerfectAmethysts: true
    skipPerfectRubies: true
backtotown:
    noHpPotions: true
    noMpPotions: true
    mercDied: true
    equipmentBroken: false
