package stat

type Stat int16

const (
	Strength Stat = iota
	Energy
	Dexterity
	Vitality
	StatPoints
	SkillPoints
	Life
	MaxLife
	Mana
	MaxMana
	Stamina
	MaxStamina
	Level
	Experience
	Gold
	StashGold
	EnhancedDefense
	EnhancedDamageMax
	EnhancedDamage
	AttackRating
	ChanceToBlock
	MinDamage
	MaxDamage
	TwoHandedMinDamage
	TwoHandedMaxDamage
	DamagePercent
	ManaRecovery
	ManaRecoveryBonus
	StaminaRecoveryBonus
	LastExp
	NextExp
	Defense
	DefenseVsMissiles
	DefenseVsHth
	NormalDamageReduction
	MagicDamageReduction
	DamageReduced
	MagicResist
	MaxMagicResist
	FireResist
	MaxFireResist
	LightningResist
	MaxLightningResist
	ColdResist
	MaxColdResist
	PoisonResist
	MaxPoisonResist
	DamageAura
	FireMinDamage
	FireMaxDamage
	LightningMinDamage
	LightningMaxDamage
	MagicMinDamage
	MagicMaxDamage
	ColdMinDamage
	ColdMaxDamage
	ColdLength
	PoisonMinDamage
	PoisonMaxDamage
	PoisonLength
	LifeSteal
	LifeStealMax
	ManaSteal
	ManaStealMax
	StaminaDrainMinDamage
	StaminaDrainMaxDamage
	StunLength
	VelocityPercent
	AttackRate
	OtherAnimRate
	Quantity
	Value
	Durability
	MaxDurability
	ReplenishLife
	MaxDurabilityPercent
	MaxLifePercent
	MaxManaPercent
	AttackerTakesDamage
	GoldFind
	MagicFind
	Knockback
	TimeDuration
	AddClassSkills
	Unused84
	AddExperience
	LifeAfterEachKill
	ReducePrices
	DoubleHerbDuration
	LightRadius
	LightColor
	Requirements
	LevelRequire
	IncreasedAttackSpeed
	LevelRequirePercent
	LastBlockFrame
	FasterRunWalk
	NonClassSkill
	State
	FasterHitRecovery
	PlayerCount
	PoisonOverrideLength
	FasterBlockRate
	BypassUndead
	BypassDemons
	FasterCastRate
	BypassBeasts
	SingleSkill
	SlainMonstersRestInPeace
	CurseResistance
	PoisonLengthReduced
	NormalDamage
	HitCausesMonsterToFlee
	HitBlindsTarget
	DamageTakenGoesToMana
	IgnoreTargetsDefense
	TargetDefense
	PreventMonsterHeal
	HalfFreezeDuration
	AttackRatingPercent
	MonsterDefensePerHit
	DemonDamagePercent
	UndeadDamagePercent
	DemonAttackRating
	UndeadAttackRating
	Throwable
	FireSkills
	AllSkills
	AttackerTakesLightDamage
	IronMaidenLevel
	LifeTapLevel
	ThornsPercent
	BoneArmor
	BoneArmorMax
	FreezesTarget
	OpenWounds
	CrushingBlow
	KickDamage
	ManaAfterKill
	HealAfterDemonKill
	ExtraBlood
	DeadlyStrike
	AbsorbFirePercent
	AbsorbFire
	AbsorbLightningPercent
	AbsorbLightning
	AbsorbMagicPercent
	AbsorbMagic
	AbsorbColdPercent
	AbsorbCold
	SlowsTarget
	Aura
	Indestructible
	CannotBeFrozen
	SlowerStaminaDrain
	Reanimate
	Pierce
	MagicArrow
	ExplosiveArrow
	ThrowMinDamage
	ThrowMaxDamage
	SkillHandofAthena
	SkillStaminaPercent
	SkillPassiveStaminaPercent
	SkillConcentration
	SkillEnchant
	SkillPierce
	SkillConviction
	SkillChillingArmor
	SkillFrenzy
	SkillDecrepify
	SkillArmorPercent
	Alignment
	Target0
	Target1
	GoldLost
	ConverisonLevel
	ConverisonMaxHP
	UnitDooverlay
	AttackVsMonType
	DamageVsMonType
	Fade
	ArmorOverridePercent
	Unused183
	Unused184
	Unused185
	Unused186
	Unused187
	AddSkillTab
	Unused189
	Unused190
	Unused191
	Unused192
	Unused193
	NumSockets
	SkillOnAttack
	SkillOnKill
	SkillOnDeath
	SkillOnHit
	SkillOnLevelUp
	Unused200
	SkillOnGetHit
	Unused202
	Unused203
	ItemChargedSkill
	Unused205
	Unused206
	Unused207
	Unused208
	Unused209
	Unused210
	Unused211
	Unused212
	Unused213
	DefensePerLevel
	ArmorPercentPerLevel
	LifePerLevel
	ManaPerLevel
	MaxDamagePerLevel
	MaxDamagePercentPerLevel
	StrengthPerLevel
	DexterityPerLevel
	EnergyPerLevel
	VitalityPerLevel
	AttackRatingPerLevel
	AttackRatingPercentPerLevel
	ColdDamageMaxPerLevel
	FireDamageMaxPerLevel
	LightningDamageMaxPerLevel
	PoisonDamageMaxPerLevel
	ResistColdPerLevel
	ResistFirePerLevel
	ResistLightningPerLevel
	ResistPoisonPerLevel
	AbsorbColdPerLevel
	AbsorbFirePerLevel
	AbsorbLightningPerLevel
	AbsorbPoisonPerLevel
	ThornsPerLevel
	ExtraGoldPerLevel
	MagicFindPerLevel
	RegenStaminaPerLevel
	StaminaPerLevel
	DamageDemonPerLevel
	DamageUndeadPerLevel
	AttackRatingDemonPerLevel
	AttackRatingUndeadPerLevel
	CrushingBlowPerLevel
	OpenWoundsPerLevel
	KickDamagePerLevel
	DeadlyStrikePerLevel
	FindGemsPerLevel
	ReplenishDurability
	ReplenishQuantity
	ExtraStack
	FindItem
	SlashDamage
	SlashDamagePercent
	CrushDamage
	CrushDamagePercent
	ThrustDamage
	ThrustDamagePercent
	AbsorbSlash
	AbsorbCrush
	AbsorbThrust
	AbsorbSlashPercent
	AbsorbCrushPercent
	AbsorbThrustPercent
	ArmorByTime
	ArmorPercentByTime
	LifeByTime
	ManaByTime
	MaxDamageByTime
	MaxDamagePercentByTime
	StrengthByTime
	DexterityByTime
	EnergyByTime
	VitalityByTime
	AttackRatingByTime
	AttackRatingPercentByTime
	ColdDamageMaxByTime
	FireDamageMaxByTime
	LightningDamageMaxByTime
	PoisonDamageMaxByTime
	ResistColdByTime
	ResistFireByTime
	ResistLightningByTime
	ResistPoisonByTime
	AbsorbColdByTime
	AbsorbFireByTime
	AbsorbLightningByTime
	AbsorbPoisonByTime
	FindGoldByTime
	MagicFindByTime
	RegenStaminaByTime
	StaminaByTime
	DamageDemonByTime
	DamageUndeadByTime
	AttackRatingDemonByTime
	AttackRatingUndeadByTime
	CrushingBlowByTime
	OpenWoundsByTime
	KickDamageByTime
	DeadlyStrikeByTime
	FindGemsByTime
	PierceCold
	PierceFire
	PierceLightning
	PiercePoison
	DamageVsMonster
	DamagePercentVsMonster
	AttackRatingVsMonster
	AttackRatingPercentVsMonster
	AcVsMonster
	AcPercentVsMonster
	FireLength
	BurningMin
	BurningMax
	ProgressiveDamage
	ProgressiveSteal
	ProgressiveOther
	ProgressiveFire
	ProgressiveCold
	ProgressiveLightning
	ExtraCharges
	ProgressiveAttackRating
	PoisonCount
	DamageFrameRate
	PierceIdx
	FireSkillDamage
	LightningSkillDamage
	ColdSkillDamage
	PoisonSkillDamage
	EnemyFireResist
	EnemyLightningResist
	EnemyColdResist
	EnemyPoisonResist
	PassiveCriticalStrike
	PassiveDodge
	PassiveAvoid
	PassiveEvade
	PassiveWarmth
	PassiveMasteryMeleeAttackRating
	PassiveMasteryMeleeDamage
	PassiveMasteryMeleeCritical
	PassiveMasteryThrowAttackRating
	PassiveMasteryThrowDamage
	PassiveMasteryThrowCritical
	PassiveWeaponBlock
	SummonResist
	ModifierListSkill
	ModifierListLevel
	LastSentHPPercent
	SourceUnitType
	SourceUnitID
	ShortParam1
	QuestItemDifficulty
	PassiveMagicMastery
	PassiveMagicPierce
)
