package config

var AvailableRecipes = []string{
	// List out all the recipe names from cube_recipes.go
	"Upgrade Chipped Amethyst",
	"Upgrade Chipped Diamond",
	"Upgrade Chipped Emerald",
	"Upgrade Chipped Ruby",
	"Upgrade Chipped Sapphire",
	"Upgrade Chipped Topaz",
	"Upgrade Chipped Skull",
	"Upgrade Flawed Amethyst",
	"Upgrade Flawed Diamond",
	"Upgrade Flawed Emerald",
	"Upgrade Flawed Ruby",
	"Upgrade Flawed Sapphire",
	"Upgrade Flawed Topaz",
	"Upgrade Flawed Skull",
	"Upgrade Amethyst",
	"Upgrade Diamond",
	"Upgrade Emerald",
	"Upgrade Ruby",
	"Upgrade Sapphire",
	"Upgrade Topaz",
	"Upgrade Skull",
	"Upgrade Flawless Amethyst",
	"Upgrade Flawless Diamond",
	"Upgrade Flawless Emerald",
	"Upgrade Flawless Ruby",
	"Upgrade Flawless Sapphire",
	"Upgrade Flawless Topaz",
	"Upgrade Flawless Skull",
	"Token of Absolution",
	"Upgrade El",
	"Upgrade Eld",
	"Upgrade Tir",
	"Upgrade Nef",
	"Upgrade Eth",
	"Upgrade Ith",
	"Upgrade Tal",
	"Upgrade Ral",
	"Upgrade Ort",
	"Upgrade Thul",
	"Upgrade Amn",
	"Upgrade Sol",
	"Upgrade Shael",
	"Upgrade Dol",
	"Upgrade Hel",
	"Upgrade Io",
	"Upgrade Lum",
	"Upgrade Ko",
	"Upgrade Fal",
	"Upgrade Lem",
	"Upgrade Pul",
	"Upgrade Um",
	"Upgrade Mal",
	"Upgrade Ist",
	"Upgrade Gul",
	"Upgrade Vex",
	"Upgrade Ohm",
	"Upgrade Lo",
	"Upgrade Sur",
	"Upgrade Ber",
	"Upgrade Jah",
	"Upgrade Cham",
	"Reroll GrandCharms",
	"Caster Amulet",
	"Caster Ring",
	// "Blood Gloves",
	// "Blood Boots",
	// "Blood Belt",
	// "Blood Helm",
	// "Blood Armor",
	// "Blood Weapon",
	// "Safety Shield",
	// "Safety Armor",
	// "Safety Boots",
	// "Safety Gloves",
	// "Safety Belt",
	// "Safety Helm",
	// "Hitpower Gloves",
	// "Hitpower Boots",
	// "Hitpower Belt",
	// "Hitpower Helm",
	// "Hitpower Armor",
	// "Hitpower Shield",
}

// Crafting recipes are available within cubing_recipes.go but were missing here.
// Not sure if this was/is intentional, added them for the sake of completeness
