// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: mapassist.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type R struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *R) Reset() {
	*x = R{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapassist_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *R) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*R) ProtoMessage() {}

func (x *R) ProtoReflect() protoreflect.Message {
	mi := &file_mapassist_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use R.ProtoReflect.Descriptor instead.
func (*R) Descriptor() ([]byte, []int) {
	return file_mapassist_proto_rawDescGZIP(), []int{0}
}

type Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Area             string             `protobuf:"bytes,1,opt,name=area,proto3" json:"area,omitempty"`
	AreaOrigin       *Position          `protobuf:"bytes,2,opt,name=area_origin,json=areaOrigin,proto3" json:"area_origin,omitempty"`
	Status           *Status            `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Corpses          []*Corpse          `protobuf:"bytes,4,rep,name=corpses,proto3" json:"corpses,omitempty"`
	PlayerUnit       *PlayerUnit        `protobuf:"bytes,5,opt,name=player_unit,json=playerUnit,proto3" json:"player_unit,omitempty"`
	Items            []*Item            `protobuf:"bytes,6,rep,name=items,proto3" json:"items,omitempty"`
	Objects          []*Object          `protobuf:"bytes,7,rep,name=objects,proto3" json:"objects,omitempty"`
	Monsters         []*Monster         `protobuf:"bytes,8,rep,name=monsters,proto3" json:"monsters,omitempty"`
	Npcs             []*NPC             `protobuf:"bytes,9,rep,name=npcs,proto3" json:"npcs,omitempty"`
	CollisionGrid    []*CollisionGrid   `protobuf:"bytes,10,rep,name=collision_grid,json=collisionGrid,proto3" json:"collision_grid,omitempty"`
	MenuOpen         *MenuOpen          `protobuf:"bytes,11,opt,name=menu_open,json=menuOpen,proto3" json:"menu_open,omitempty"`
	PointsOfInterest []*PointOfInterest `protobuf:"bytes,12,rep,name=points_of_interest,json=pointsOfInterest,proto3" json:"points_of_interest,omitempty"`
	AdjacentLevels   []*AdjacentLevel   `protobuf:"bytes,13,rep,name=adjacent_levels,json=adjacentLevels,proto3" json:"adjacent_levels,omitempty"`
}

func (x *Data) Reset() {
	*x = Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapassist_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_mapassist_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_mapassist_proto_rawDescGZIP(), []int{1}
}

func (x *Data) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *Data) GetAreaOrigin() *Position {
	if x != nil {
		return x.AreaOrigin
	}
	return nil
}

func (x *Data) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Data) GetCorpses() []*Corpse {
	if x != nil {
		return x.Corpses
	}
	return nil
}

func (x *Data) GetPlayerUnit() *PlayerUnit {
	if x != nil {
		return x.PlayerUnit
	}
	return nil
}

func (x *Data) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Data) GetObjects() []*Object {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *Data) GetMonsters() []*Monster {
	if x != nil {
		return x.Monsters
	}
	return nil
}

func (x *Data) GetNpcs() []*NPC {
	if x != nil {
		return x.Npcs
	}
	return nil
}

func (x *Data) GetCollisionGrid() []*CollisionGrid {
	if x != nil {
		return x.CollisionGrid
	}
	return nil
}

func (x *Data) GetMenuOpen() *MenuOpen {
	if x != nil {
		return x.MenuOpen
	}
	return nil
}

func (x *Data) GetPointsOfInterest() []*PointOfInterest {
	if x != nil {
		return x.PointsOfInterest
	}
	return nil
}

func (x *Data) GetAdjacentLevels() []*AdjacentLevel {
	if x != nil {
		return x.AdjacentLevels
	}
	return nil
}

type PointOfInterest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Position *Position `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *PointOfInterest) Reset() {
	*x = PointOfInterest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapassist_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PointOfInterest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointOfInterest) ProtoMessage() {}

func (x *PointOfInterest) ProtoReflect() protoreflect.Message {
	mi := &file_mapassist_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointOfInterest.ProtoReflect.Descriptor instead.
func (*PointOfInterest) Descriptor() ([]byte, []int) {
	return file_mapassist_proto_rawDescGZIP(), []int{2}
}

func (x *PointOfInterest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PointOfInterest) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

type AdjacentLevel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Area      string      `protobuf:"bytes,1,opt,name=area,proto3" json:"area,omitempty"`
	Positions []*Position `protobuf:"bytes,2,rep,name=positions,proto3" json:"positions,omitempty"`
	IsPortal  bool        `protobuf:"varint,3,opt,name=is_portal,json=isPortal,proto3" json:"is_portal,omitempty"`
}

func (x *AdjacentLevel) Reset() {
	*x = AdjacentLevel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapassist_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdjacentLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjacentLevel) ProtoMessage() {}

func (x *AdjacentLevel) ProtoReflect() protoreflect.Message {
	mi := &file_mapassist_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjacentLevel.ProtoReflect.Descriptor instead.
func (*AdjacentLevel) Descriptor() ([]byte, []int) {
	return file_mapassist_proto_rawDescGZIP(), []int{3}
}

func (x *AdjacentLevel) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *AdjacentLevel) GetPositions() []*Position {
	if x != nil {
		return x.Positions
	}
	return nil
}

func (x *AdjacentLevel) GetIsPortal() bool {
	if x != nil {
		return x.IsPortal
	}
	return false
}

type MenuOpen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inventory   bool `protobuf:"varint,1,opt,name=inventory,proto3" json:"inventory,omitempty"`
	NpcInteract bool `protobuf:"varint,2,opt,name=npc_interact,json=npcInteract,proto3" json:"npc_interact,omitempty"`
	NpcShop     bool `protobuf:"varint,3,opt,name=npc_shop,json=npcShop,proto3" json:"npc_shop,omitempty"`
	Stash       bool `protobuf:"varint,4,opt,name=stash,proto3" json:"stash,omitempty"`
	Waypoint    bool `protobuf:"varint,5,opt,name=waypoint,proto3" json:"waypoint,omitempty"`
}

func (x *MenuOpen) Reset() {
	*x = MenuOpen{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapassist_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MenuOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuOpen) ProtoMessage() {}

func (x *MenuOpen) ProtoReflect() protoreflect.Message {
	mi := &file_mapassist_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuOpen.ProtoReflect.Descriptor instead.
func (*MenuOpen) Descriptor() ([]byte, []int) {
	return file_mapassist_proto_rawDescGZIP(), []int{4}
}

func (x *MenuOpen) GetInventory() bool {
	if x != nil {
		return x.Inventory
	}
	return false
}

func (x *MenuOpen) GetNpcInteract() bool {
	if x != nil {
		return x.NpcInteract
	}
	return false
}

func (x *MenuOpen) GetNpcShop() bool {
	if x != nil {
		return x.NpcShop
	}
	return false
}

func (x *MenuOpen) GetStash() bool {
	if x != nil {
		return x.Stash
	}
	return false
}

func (x *MenuOpen) GetWaypoint() bool {
	if x != nil {
		return x.Waypoint
	}
	return false
}

type CollisionGrid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Walkable []bool `protobuf:"varint,1,rep,packed,name=walkable,proto3" json:"walkable,omitempty"`
}

func (x *CollisionGrid) Reset() {
	*x = CollisionGrid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapassist_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollisionGrid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollisionGrid) ProtoMessage() {}

func (x *CollisionGrid) ProtoReflect() protoreflect.Message {
	mi := &file_mapassist_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollisionGrid.ProtoReflect.Descriptor instead.
func (*CollisionGrid) Descriptor() ([]byte, []int) {
	return file_mapassist_proto_rawDescGZIP(), []int{5}
}

func (x *CollisionGrid) GetWalkable() []bool {
	if x != nil {
		return x.Walkable
	}
	return nil
}

type NPC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Positions []*Position `protobuf:"bytes,2,rep,name=positions,proto3" json:"positions,omitempty"`
}

func (x *NPC) Reset() {
	*x = NPC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapassist_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NPC) ProtoMessage() {}

func (x *NPC) ProtoReflect() protoreflect.Message {
	mi := &file_mapassist_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NPC.ProtoReflect.Descriptor instead.
func (*NPC) Descriptor() ([]byte, []int) {
	return file_mapassist_proto_rawDescGZIP(), []int{6}
}

func (x *NPC) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NPC) GetPositions() []*Position {
	if x != nil {
		return x.Positions
	}
	return nil
}

type Monster struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Position   *Position `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Hovered    bool      `protobuf:"varint,3,opt,name=hovered,proto3" json:"hovered,omitempty"`
	Immunities []string  `protobuf:"bytes,4,rep,name=immunities,proto3" json:"immunities,omitempty"`
	Type       string    `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *Monster) Reset() {
	*x = Monster{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapassist_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Monster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Monster) ProtoMessage() {}

func (x *Monster) ProtoReflect() protoreflect.Message {
	mi := &file_mapassist_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Monster.ProtoReflect.Descriptor instead.
func (*Monster) Descriptor() ([]byte, []int) {
	return file_mapassist_proto_rawDescGZIP(), []int{7}
}

func (x *Monster) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Monster) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Monster) GetHovered() bool {
	if x != nil {
		return x.Hovered
	}
	return false
}

func (x *Monster) GetImmunities() []string {
	if x != nil {
		return x.Immunities
	}
	return nil
}

func (x *Monster) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type Object struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Position   *Position `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Hovered    bool      `protobuf:"varint,3,opt,name=hovered,proto3" json:"hovered,omitempty"`
	Selectable bool      `protobuf:"varint,4,opt,name=selectable,proto3" json:"selectable,omitempty"`
	Chest      bool      `protobuf:"varint,5,opt,name=chest,proto3" json:"chest,omitempty"`
}

func (x *Object) Reset() {
	*x = Object{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapassist_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Object) ProtoMessage() {}

func (x *Object) ProtoReflect() protoreflect.Message {
	mi := &file_mapassist_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Object.ProtoReflect.Descriptor instead.
func (*Object) Descriptor() ([]byte, []int) {
	return file_mapassist_proto_rawDescGZIP(), []int{8}
}

func (x *Object) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Object) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Object) GetHovered() bool {
	if x != nil {
		return x.Hovered
	}
	return false
}

func (x *Object) GetSelectable() bool {
	if x != nil {
		return x.Selectable
	}
	return false
}

func (x *Object) GetChest() bool {
	if x != nil {
		return x.Chest
	}
	return false
}

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int32     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Position   *Position `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Name       string    `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Hovered    bool      `protobuf:"varint,4,opt,name=hovered,proto3" json:"hovered,omitempty"`
	Place      string    `protobuf:"bytes,5,opt,name=place,proto3" json:"place,omitempty"`
	Quality    string    `protobuf:"bytes,6,opt,name=quality,proto3" json:"quality,omitempty"`
	Ethereal   bool      `protobuf:"varint,7,opt,name=ethereal,proto3" json:"ethereal,omitempty"`
	Stats      []*Stat   `protobuf:"bytes,8,rep,name=stats,proto3" json:"stats,omitempty"`
	Identified bool      `protobuf:"varint,9,opt,name=identified,proto3" json:"identified,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapassist_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_mapassist_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_mapassist_proto_rawDescGZIP(), []int{9}
}

func (x *Item) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Item) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetHovered() bool {
	if x != nil {
		return x.Hovered
	}
	return false
}

func (x *Item) GetPlace() string {
	if x != nil {
		return x.Place
	}
	return ""
}

func (x *Item) GetQuality() string {
	if x != nil {
		return x.Quality
	}
	return ""
}

func (x *Item) GetEthereal() bool {
	if x != nil {
		return x.Ethereal
	}
	return false
}

func (x *Item) GetStats() []*Stat {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *Item) GetIdentified() bool {
	if x != nil {
		return x.Identified
	}
	return false
}

type PlayerUnit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Position *Position `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Skills   []*Skill  `protobuf:"bytes,3,rep,name=skills,proto3" json:"skills,omitempty"`
	Stats    []*Stat   `protobuf:"bytes,4,rep,name=stats,proto3" json:"stats,omitempty"`
	Class    string    `protobuf:"bytes,5,opt,name=class,proto3" json:"class,omitempty"`
}

func (x *PlayerUnit) Reset() {
	*x = PlayerUnit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapassist_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerUnit) ProtoMessage() {}

func (x *PlayerUnit) ProtoReflect() protoreflect.Message {
	mi := &file_mapassist_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerUnit.ProtoReflect.Descriptor instead.
func (*PlayerUnit) Descriptor() ([]byte, []int) {
	return file_mapassist_proto_rawDescGZIP(), []int{10}
}

func (x *PlayerUnit) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerUnit) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *PlayerUnit) GetSkills() []*Skill {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *PlayerUnit) GetStats() []*Stat {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *PlayerUnit) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

type Stat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value uint32 `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Stat) Reset() {
	*x = Stat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapassist_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stat) ProtoMessage() {}

func (x *Stat) ProtoReflect() protoreflect.Message {
	mi := &file_mapassist_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stat.ProtoReflect.Descriptor instead.
func (*Stat) Descriptor() ([]byte, []int) {
	return file_mapassist_proto_rawDescGZIP(), []int{11}
}

func (x *Stat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Stat) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Skill struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Points uint32 `protobuf:"varint,2,opt,name=points,proto3" json:"points,omitempty"`
}

func (x *Skill) Reset() {
	*x = Skill{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapassist_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Skill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Skill) ProtoMessage() {}

func (x *Skill) ProtoReflect() protoreflect.Message {
	mi := &file_mapassist_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Skill.ProtoReflect.Descriptor instead.
func (*Skill) Descriptor() ([]byte, []int) {
	return file_mapassist_proto_rawDescGZIP(), []int{12}
}

func (x *Skill) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Skill) GetPoints() uint32 {
	if x != nil {
		return x.Points
	}
	return 0
}

type Corpse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Hovered  bool      `protobuf:"varint,2,opt,name=hovered,proto3" json:"hovered,omitempty"`
	Position *Position `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *Corpse) Reset() {
	*x = Corpse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapassist_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Corpse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Corpse) ProtoMessage() {}

func (x *Corpse) ProtoReflect() protoreflect.Message {
	mi := &file_mapassist_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Corpse.ProtoReflect.Descriptor instead.
func (*Corpse) Descriptor() ([]byte, []int) {
	return file_mapassist_proto_rawDescGZIP(), []int{13}
}

func (x *Corpse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Corpse) GetHovered() bool {
	if x != nil {
		return x.Hovered
	}
	return false
}

func (x *Corpse) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

type Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Life        uint32 `protobuf:"varint,1,opt,name=life,proto3" json:"life,omitempty"`
	MaxLife     uint32 `protobuf:"varint,2,opt,name=max_life,json=maxLife,proto3" json:"max_life,omitempty"`
	Mana        uint32 `protobuf:"varint,3,opt,name=mana,proto3" json:"mana,omitempty"`
	MaxMana     uint32 `protobuf:"varint,4,opt,name=max_mana,json=maxMana,proto3" json:"max_mana,omitempty"`
	MercAlive   bool   `protobuf:"varint,5,opt,name=merc_alive,json=mercAlive,proto3" json:"merc_alive,omitempty"`
	MercLife    uint32 `protobuf:"varint,6,opt,name=merc_life,json=mercLife,proto3" json:"merc_life,omitempty"`
	MercMaxLife uint32 `protobuf:"varint,7,opt,name=merc_max_life,json=mercMaxLife,proto3" json:"merc_max_life,omitempty"`
}

func (x *Status) Reset() {
	*x = Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapassist_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_mapassist_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_mapassist_proto_rawDescGZIP(), []int{14}
}

func (x *Status) GetLife() uint32 {
	if x != nil {
		return x.Life
	}
	return 0
}

func (x *Status) GetMaxLife() uint32 {
	if x != nil {
		return x.MaxLife
	}
	return 0
}

func (x *Status) GetMana() uint32 {
	if x != nil {
		return x.Mana
	}
	return 0
}

func (x *Status) GetMaxMana() uint32 {
	if x != nil {
		return x.MaxMana
	}
	return 0
}

func (x *Status) GetMercAlive() bool {
	if x != nil {
		return x.MercAlive
	}
	return false
}

func (x *Status) GetMercLife() uint32 {
	if x != nil {
		return x.MercLife
	}
	return 0
}

func (x *Status) GetMercMaxLife() uint32 {
	if x != nil {
		return x.MercMaxLife
	}
	return 0
}

type Position struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Position) Reset() {
	*x = Position{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapassist_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_mapassist_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_mapassist_proto_rawDescGZIP(), []int{15}
}

func (x *Position) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

var File_mapassist_proto protoreflect.FileDescriptor

var file_mapassist_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6d, 0x61, 0x70, 0x61, 0x73, 0x73, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0x03, 0x0a, 0x01, 0x52, 0x22, 0xc0, 0x04, 0x0a, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x65, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x65, 0x61, 0x12, 0x2e, 0x0a, 0x0b, 0x61, 0x72, 0x65, 0x61,
	0x5f, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x61, 0x72,
	0x65, 0x61, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x12, 0x23, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x25, 0x0a,
	0x07, 0x63, 0x6f, 0x72, 0x70, 0x73, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6f, 0x72, 0x70, 0x73, 0x65, 0x52, 0x07, 0x63, 0x6f, 0x72,
	0x70, 0x73, 0x65, 0x73, 0x12, 0x30, 0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x75,
	0x6e, 0x69, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x55, 0x6e, 0x69, 0x74, 0x12, 0x1f, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18,
	0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x25, 0x0a, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x12, 0x28,
	0x0a, 0x08, 0x6d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x52, 0x08,
	0x6d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x73, 0x12, 0x1c, 0x0a, 0x04, 0x6e, 0x70, 0x63, 0x73,
	0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4e, 0x50, 0x43,
	0x52, 0x04, 0x6e, 0x70, 0x63, 0x73, 0x12, 0x39, 0x0a, 0x0e, 0x63, 0x6f, 0x6c, 0x6c, 0x69, 0x73,
	0x69, 0x6f, 0x6e, 0x5f, 0x67, 0x72, 0x69, 0x64, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x47, 0x72,
	0x69, 0x64, 0x52, 0x0d, 0x63, 0x6f, 0x6c, 0x6c, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x69,
	0x64, 0x12, 0x2a, 0x0a, 0x09, 0x6d, 0x65, 0x6e, 0x75, 0x5f, 0x6f, 0x70, 0x65, 0x6e, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x65, 0x6e, 0x75, 0x4f,
	0x70, 0x65, 0x6e, 0x52, 0x08, 0x6d, 0x65, 0x6e, 0x75, 0x4f, 0x70, 0x65, 0x6e, 0x12, 0x42, 0x0a,
	0x12, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x5f, 0x6f, 0x66, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x65, 0x73, 0x74, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x50, 0x6f, 0x69, 0x6e, 0x74, 0x4f, 0x66, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x52,
	0x10, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x4f, 0x66, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73,
	0x74, 0x12, 0x3b, 0x0a, 0x0f, 0x61, 0x64, 0x6a, 0x61, 0x63, 0x65, 0x6e, 0x74, 0x5f, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x73, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x41, 0x64, 0x6a, 0x61, 0x63, 0x65, 0x6e, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x0e,
	0x61, 0x64, 0x6a, 0x61, 0x63, 0x65, 0x6e, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x73, 0x22, 0x50,
	0x0a, 0x0f, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x4f, 0x66, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x29, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x6d, 0x0a, 0x0d, 0x41, 0x64, 0x6a, 0x61, 0x63, 0x65, 0x6e, 0x74, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x65, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x61, 0x72, 0x65, 0x61, 0x12, 0x2b, 0x0a, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x50, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x22,
	0x98, 0x01, 0x0a, 0x08, 0x4d, 0x65, 0x6e, 0x75, 0x4f, 0x70, 0x65, 0x6e, 0x12, 0x1c, 0x0a, 0x09,
	0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x09, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x6e, 0x70,
	0x63, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0b, 0x6e, 0x70, 0x63, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x12, 0x19, 0x0a,
	0x08, 0x6e, 0x70, 0x63, 0x5f, 0x73, 0x68, 0x6f, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x6e, 0x70, 0x63, 0x53, 0x68, 0x6f, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x73,
	0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x73, 0x74, 0x61, 0x73, 0x68, 0x12, 0x1a,
	0x0a, 0x08, 0x77, 0x61, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x77, 0x61, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x22, 0x2b, 0x0a, 0x0d, 0x43, 0x6f,
	0x6c, 0x6c, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x77,
	0x61, 0x6c, 0x6b, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x08, 0x52, 0x08, 0x77,
	0x61, 0x6c, 0x6b, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x46, 0x0a, 0x03, 0x4e, 0x50, 0x43, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22,
	0x96, 0x01, 0x0a, 0x07, 0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x29, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x6f,
	0x76, 0x65, 0x72, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x68, 0x6f, 0x76,
	0x65, 0x72, 0x65, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x69,
	0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6d, 0x6d, 0x75, 0x6e, 0x69,
	0x74, 0x69, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x97, 0x01, 0x0a, 0x06, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x29, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x6f, 0x76, 0x65, 0x72, 0x65, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x68, 0x6f, 0x76, 0x65, 0x72, 0x65, 0x64, 0x12, 0x1e, 0x0a, 0x0a,
	0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0a, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x68, 0x65, 0x73, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x63, 0x68, 0x65,
	0x73, 0x74, 0x22, 0xfc, 0x01, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x29, 0x0a, 0x08, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x6f,
	0x76, 0x65, 0x72, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x68, 0x6f, 0x76,
	0x65, 0x72, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x71, 0x75,
	0x61, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x71, 0x75, 0x61,
	0x6c, 0x69, 0x74, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x74, 0x68, 0x65, 0x72, 0x65, 0x61, 0x6c,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x65, 0x74, 0x68, 0x65, 0x72, 0x65, 0x61, 0x6c,
	0x12, 0x1f, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x64, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65,
	0x64, 0x22, 0xa6, 0x01, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x55, 0x6e, 0x69, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x29, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x22, 0x0a, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x52, 0x06, 0x73, 0x6b, 0x69,
	0x6c, 0x6c, 0x73, 0x12, 0x1f, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x22, 0x30, 0x0a, 0x04, 0x53, 0x74,
	0x61, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x33, 0x0a, 0x05,
	0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x73, 0x22, 0x61, 0x0a, 0x06, 0x43, 0x6f, 0x72, 0x70, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x68, 0x6f, 0x76, 0x65, 0x72, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x68, 0x6f, 0x76, 0x65, 0x72, 0x65, 0x64, 0x12, 0x29, 0x0a, 0x08, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0xc6, 0x01, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x6c, 0x69, 0x66, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x6c,
	0x69, 0x66, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x61, 0x78, 0x5f, 0x6c, 0x69, 0x66, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x6d, 0x61, 0x78, 0x4c, 0x69, 0x66, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6d, 0x61, 0x6e, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x6d, 0x61,
	0x6e, 0x61, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x61, 0x78, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x6d, 0x61, 0x78, 0x4d, 0x61, 0x6e, 0x61, 0x12, 0x1d, 0x0a,
	0x0a, 0x6d, 0x65, 0x72, 0x63, 0x5f, 0x61, 0x6c, 0x69, 0x76, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x09, 0x6d, 0x65, 0x72, 0x63, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x6d, 0x65, 0x72, 0x63, 0x5f, 0x6c, 0x69, 0x66, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x08, 0x6d, 0x65, 0x72, 0x63, 0x4c, 0x69, 0x66, 0x65, 0x12, 0x22, 0x0a, 0x0d, 0x6d, 0x65, 0x72,
	0x63, 0x5f, 0x6d, 0x61, 0x78, 0x5f, 0x6c, 0x69, 0x66, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0b, 0x6d, 0x65, 0x72, 0x63, 0x4d, 0x61, 0x78, 0x4c, 0x69, 0x66, 0x65, 0x22, 0x26, 0x0a,
	0x08, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x01, 0x79, 0x32, 0x2e, 0x0a, 0x0c, 0x4d, 0x61, 0x70, 0x41, 0x73, 0x73, 0x69,
	0x73, 0x74, 0x41, 0x70, 0x69, 0x12, 0x1e, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x06, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x1a, 0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x22, 0x00, 0x42, 0x3a, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x67, 0x69, 0x6d, 0x65, 0x6e, 0x65,
	0x7a, 0x2f, 0x6b, 0x6f, 0x6f, 0x6c, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0xaa, 0x02, 0x13, 0x6b, 0x6f,
	0x6f, 0x6c, 0x6f, 0x2e, 0x6d, 0x61, 0x70, 0x61, 0x73, 0x73, 0x69, 0x73, 0x74, 0x2e, 0x61, 0x70,
	0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mapassist_proto_rawDescOnce sync.Once
	file_mapassist_proto_rawDescData = file_mapassist_proto_rawDesc
)

func file_mapassist_proto_rawDescGZIP() []byte {
	file_mapassist_proto_rawDescOnce.Do(func() {
		file_mapassist_proto_rawDescData = protoimpl.X.CompressGZIP(file_mapassist_proto_rawDescData)
	})
	return file_mapassist_proto_rawDescData
}

var file_mapassist_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_mapassist_proto_goTypes = []interface{}{
	(*R)(nil),               // 0: api.R
	(*Data)(nil),            // 1: api.Data
	(*PointOfInterest)(nil), // 2: api.PointOfInterest
	(*AdjacentLevel)(nil),   // 3: api.AdjacentLevel
	(*MenuOpen)(nil),        // 4: api.MenuOpen
	(*CollisionGrid)(nil),   // 5: api.CollisionGrid
	(*NPC)(nil),             // 6: api.NPC
	(*Monster)(nil),         // 7: api.Monster
	(*Object)(nil),          // 8: api.Object
	(*Item)(nil),            // 9: api.Item
	(*PlayerUnit)(nil),      // 10: api.PlayerUnit
	(*Stat)(nil),            // 11: api.Stat
	(*Skill)(nil),           // 12: api.Skill
	(*Corpse)(nil),          // 13: api.Corpse
	(*Status)(nil),          // 14: api.Status
	(*Position)(nil),        // 15: api.Position
}
var file_mapassist_proto_depIdxs = []int32{
	15, // 0: api.Data.area_origin:type_name -> api.Position
	14, // 1: api.Data.status:type_name -> api.Status
	13, // 2: api.Data.corpses:type_name -> api.Corpse
	10, // 3: api.Data.player_unit:type_name -> api.PlayerUnit
	9,  // 4: api.Data.items:type_name -> api.Item
	8,  // 5: api.Data.objects:type_name -> api.Object
	7,  // 6: api.Data.monsters:type_name -> api.Monster
	6,  // 7: api.Data.npcs:type_name -> api.NPC
	5,  // 8: api.Data.collision_grid:type_name -> api.CollisionGrid
	4,  // 9: api.Data.menu_open:type_name -> api.MenuOpen
	2,  // 10: api.Data.points_of_interest:type_name -> api.PointOfInterest
	3,  // 11: api.Data.adjacent_levels:type_name -> api.AdjacentLevel
	15, // 12: api.PointOfInterest.position:type_name -> api.Position
	15, // 13: api.AdjacentLevel.positions:type_name -> api.Position
	15, // 14: api.NPC.positions:type_name -> api.Position
	15, // 15: api.Monster.position:type_name -> api.Position
	15, // 16: api.Object.position:type_name -> api.Position
	15, // 17: api.Item.position:type_name -> api.Position
	11, // 18: api.Item.stats:type_name -> api.Stat
	15, // 19: api.PlayerUnit.position:type_name -> api.Position
	12, // 20: api.PlayerUnit.skills:type_name -> api.Skill
	11, // 21: api.PlayerUnit.stats:type_name -> api.Stat
	15, // 22: api.Corpse.position:type_name -> api.Position
	0,  // 23: api.MapAssistApi.GetData:input_type -> api.R
	1,  // 24: api.MapAssistApi.GetData:output_type -> api.Data
	24, // [24:25] is the sub-list for method output_type
	23, // [23:24] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_mapassist_proto_init() }
func file_mapassist_proto_init() {
	if File_mapassist_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mapassist_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*R); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapassist_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapassist_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PointOfInterest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapassist_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdjacentLevel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapassist_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MenuOpen); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapassist_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollisionGrid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapassist_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NPC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapassist_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Monster); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapassist_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Object); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapassist_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapassist_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerUnit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapassist_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapassist_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Skill); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapassist_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Corpse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapassist_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapassist_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Position); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mapassist_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mapassist_proto_goTypes,
		DependencyIndexes: file_mapassist_proto_depIdxs,
		MessageInfos:      file_mapassist_proto_msgTypes,
	}.Build()
	File_mapassist_proto = out.File
	file_mapassist_proto_rawDesc = nil
	file_mapassist_proto_goTypes = nil
	file_mapassist_proto_depIdxs = nil
}
